# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iOS-TechPost1' do
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'RealmSwift'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
end

target 'iOS-TechPost1Tests' do

end

target 'iOS-TechPost1UITests' do

end
